### ISSUE TITLE
project_to_nodes = true with quadratic elements.

### ISSUE THREAD

**Issue by lijas** [Ferrite-FEM/Ferrite.jl#440] opened 2022-04-05 06:20 UTC
Running `include("docs/src/literate/postprocessing.jl")` with QuadraticQuadrilaterals (and with quadratic interpolation), and `project_to_nodes=true` when doing the L2projection, will result in values with `NaN` for the projected values.

I think it is becuse the proj.node2dof_map only stores the "corner" nodes of the cell: https://github.com/Ferrite-FEM/Ferrite.jl/blob/8ce381e5dc7b0e424f14ddf63ee60897828650d0/src/L2_projection.jl#L212

**Comment by termi-official** [comment] 2022-04-05 10:38
Duplicate of #380 ?

**Closed** 2022-04-05 10:41 UTC
